const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const counsellorProgressSchema = new Schema({
    userId: {
        type: Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        unique: true
    },
    currentTask: {
        type: Number,
        enum: [0, 1, 2, 3, 4],
        default: 0
    },
    task0: {
        finalized: { type: Boolean, default: false },
        selectedCountry: { type: String },
        proposedCountries: [{
            country: String,
            reason: String,
            avgTuition: String,
            universitiesCount: Number
        }]
    },
    task1: {
        finalized: { type: Boolean, default: false },
        intakeYear: { type: Number },
        universityIds: [{ type: Schema.Types.ObjectId, ref: 'University' }],
        proposedList: [{
            _id: Schema.Types.ObjectId,
            name: String,
            country: String,
            city: String,
            category: String,
            ranking: Number,
            fieldsOfStudy: [String],
            degreeLevels: [String],
            requirements: Schema.Types.Mixed,
            tuitionFee: Schema.Types.Mixed,
            acceptanceRate: Number
        }]
    },
    task2: {
        completed: { type: Boolean, default: false },
        requiredExams: [Schema.Types.Mixed], // can store strings or objects with min scores
        completedExams: [Schema.Types.Mixed], // can store submitted scores { exam, score }
        requiredExamsPlan: Schema.Types.Mixed, // per-university plan generated by AI
        completedScores: Schema.Types.Mixed // map of exam -> latest score
    },
    task3: {
        completed: { type: Boolean, default: false }
    },
    task4: {
        completed: { type: Boolean, default: false },
        currentUniIndex: { type: Number, default: 0 },
        currentDocType: { type: String, enum: ['sop', 'lors', 'resume'], default: 'sop' },
        byUniversity: [{
            universityId: Schema.Types.ObjectId,
            universityName: String,
            sop: { type: Boolean, default: false },
            lors: { type: Boolean, default: false },
            resume: { type: Boolean, default: false }
        }]
    },
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }
});

counsellorProgressSchema.pre('save', function (next) {
    this.updatedAt = Date.now();
    next();
});

const CounsellorProgress = mongoose.model('CounsellorProgress', counsellorProgressSchema);
module.exports = CounsellorProgress;
